### ISSUE TITLE
Infinite loop in getOrders

### ISSUE THREAD

**Issue by GingkathFox** [GingkathFox/EveShopper#6]
There is a infinite loop in `getOrders`, in the `incr()` function. for some reason, moving `j++` to the top fixes it.

**Comment by insuusvenerati** [comment]
I'm having a hard time understanding the flow of the function. I'll take a look when I get home.

**Comment by GingkathFox** [comment]
yeah, ive tried to clean it up xd

**Comment by GingkathFox** [comment]
solved by getting a sleep function and converting to loop
